# Generated by Django 6.0 on 2026-01-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_theme", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="themestock",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="편입 시각"
            ),
        ),
    ]
